spring:
  application:
    name: "core-banking-service"
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: 7112
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
    port: 8092
eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8081/eureka


info:
    app:
      name: ${spring.application.name}