server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yash-a11y/Distributed-banking-config.git
          search-paths: config
          default-label: master