app:
  config:
    keycloak:
      url: http://localhost:8080/auth
      realm: distributed-internet-banking
spring:
  application:
    name: Banking-api-getway

  # Gateway Configurations
  cloud:
    gateway:
      routes:
        ## USER SERVICE
        - id: Banking-user-service
          uri: lb://Banking-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

#        ## FUND TRANSFER SERVICE
#        - id: internet-banking-fund-transfer-service
#          uri: lb://internet-banking-fund-transfer-service
#          predicates:
#            - Path=/fund-transfer/**
#          filters:
#            - StripPrefix=1

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          banking-core-client:
            provider: keycloak
            client-id: banking-core-client
            client-secret: jXXIc7UZEiTkJet5vfCR5cOfuLjbsHPT
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true
