server:
  port: 8085
spring:
  application:
    name: utility-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_utility_payment_service
    username: root
    password: 7112
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

