app:
  config:
    keycloak:
      server-url: http://localhost:8080/auth
      realm: distributed-internet-banking
      clientId: internet-banking-api-client
      client-secret: oNfNYeAPJXGV90GLq9mW6Vto8vP5vtvN
spring:
  application:
    name: Banking-user-service  # Change for each microservice

server:
  port: 8083  # Change port for each microservice

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true
